// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'std.experimental.rc', kind: "module", path: './std/experimental/rc.html', attributes: []},
{name: 'std.experimental.rc.RC', kind: "structdeclaration", path: './std/experimental/rc/RC.html', attributes: []},
{name: 'std.experimental.rc.RC.get', kind: "functiondeclaration", path: './std/experimental/rc/RC.get.html', attributes: ["ref"]},
{name: 'std.experimental.rc.RC.isNull', kind: "functiondeclaration", path: './std/experimental/rc/RC.isNull.html', attributes: ["const"]},
{name: 'std.experimental.rc.RC.nullify', kind: "functiondeclaration", path: './std/experimental/rc/RC.nullify.html', attributes: []},
{name: 'std.experimental.rc.RC.refCount', kind: "functiondeclaration", path: './std/experimental/rc/RC.refCount.html', attributes: ["const"]},
{name: 'std.experimental.rc.RC.this', kind: "functiondeclaration", path: './std/experimental/rc/RC.this.html', attributes: []},
{name: 'std.experimental.rc.RC.weakCount', kind: "functiondeclaration", path: './std/experimental/rc/RC.weakCount.html', attributes: ["const"]},
{name: 'std.experimental.rc.Unique', kind: "structdeclaration", path: './std/experimental/rc/Unique.html', attributes: []},
{name: 'std.experimental.rc.Weak', kind: "structdeclaration", path: './std/experimental/rc/Weak.html', attributes: []},
{name: 'std.experimental.rc.Weak.isNull', kind: "functiondeclaration", path: './std/experimental/rc/Weak.isNull.html', attributes: ["const"]},
{name: 'std.experimental.rc.Weak.nullify', kind: "functiondeclaration", path: './std/experimental/rc/Weak.nullify.html', attributes: []},
{name: 'std.experimental.rc.Weak.this', kind: "functiondeclaration", path: './std/experimental/rc/Weak.this.html', attributes: []},
];
